apiVersion: v1
kind: Service
metadata:
  name: pharmaco-chatbot-service
spec:
  selector:
    app: pharmaco-chatbot
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
