apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.Ns }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        name: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: shiva9921/pharmaco:2
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: pharmaco-config-db         
              key: MYSQL_HOST 
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: pharmaco-config-db        
              key: MYSQL_DB 
 
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: pharmaco-config-db        
              key: MYSQL_USER

        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pharmaco-config-db
              key: MYSQL_PASSWORD
              
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.Ns }}
spec:
  selector:
    app: 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: ClientIP  # Set session affinity to ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # Set the session timeout (optional)