apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmaco
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  replicas: {{ .Values.pharmaco.replicas }}
  selector:
    matchLabels:
      app: pharmaco
  template:
    metadata:
      labels:
        app: pharmaco
    spec:
      containers:
      - name: pharmaco
        image: {{ .Values.pharmaco.image.repository }}:{{ .Values.pharmaco.image.tag }}
        imagePullPolicy: {{ .Values.pharmaco.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.pharmaco.service.targetPort }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.pharmaco.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.pharmaco.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 20
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: pharmaco-config-db
              key: MYSQL_HOST
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: pharmaco-config-db
              key: MYSQL_DB
        - name: CHATBOT_URL
          valueFrom:
            configMapKeyRef:
              name: pharmaco-config-db
              key: CHATBOT_URL
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: pharmaco-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pharmaco-secret
              key: MYSQL_PASSWORD
