################
# ISTIO
#################

# Gateway
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: pharmaco-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pharmaco-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - pharmaco-gateway
  http:
  - name: pharmaco route
    route:
      - destination:
          host: pharmaco-service
          subset: v1
        weight: 100

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pharmaco-destination-1
spec:
  host: pharmaco-service
  subsets:
  - name: v1
    labels:
      app: pharmaco
      version: v1
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN