apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pharmaco-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: pharmaco-config-db
              key: MYSQL_DB
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: pharmaco-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pharmaco-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
