apiVersion: v1
kind: Secret
metadata:
  name: pharmaco-secret
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysql.user | b64enc }}
  MYSQL_PASSWORD: MTIzNDU2Nzg=   # Base64 encoded password 
  MYSQL_ROOT_PASSWORD: MTIzNDU2Nzg=
