apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/on/host"  # Replace with the actual path on your host


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



---




apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest  
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: pharmaco-config-db         
              key: MYSQL_HOST 
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: pharmaco-config-db        
              key: MYSQL_DB 
 
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: pharmaco-secret
              key:  MYSQL_USER
              
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pharmaco-config-db
              key: MYSQL_PASSWORD

        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
